<?php

namespace Api\Enum;

enum NotificationCategory: string
{
    case OUTAGE_CREATED = 'OUTAGE_CREATED';
    case OUTAGE_UPDATED = 'OUTAGE_UPDATED';
    case OUTAGE_DELETED = 'OUTAGE_DELETED';
    case PAYMENT_PAIRING_RESULT_CHANGE = 'PAYMENT_PAIRING_RESULT_CHANGE';
    case PAYMENT_RESULT_CODE_CHANGE = 'PAYMENT_RESULT_CODE_CHANGE';
}
